### PR TITLE
feat: make it easier to navigate to a specific route in navigator

### LINKED ISSUE #90: Being able to specify a stacks route from another stack
I ran into an issue where I have a root stack, and two children stacks as part of this parent stack. When I'm in one of the children stack and want to navigate to another children stack, but a specific screen of that other children stack i'm currently unable to unless I dynamically set the `initialRouteName`. However this seems like an odd way to do that.

I wish that I could do something like:
```js
navigate.push("Auth/Login");
```

The other childrens stack is named `Auth` and it's child screen is called `Login`. So in this case i'm saying go to this stack called `Auth` but specifically render the `Login` screen in that stack.

@satya164

### LINKED ISSUE #6723: Being able to specify a stacks route from another stack
I ran into an issue where I have a root stack, and two children stacks as part of this parent stack. When I'm in one of the children stack and want to navigate to another children stack, but a specific screen of that other children stack i'm currently unable to unless I dynamically set the `initialRouteName`. However this seems like an odd way to do that.

I wish that I could do something like:
```js
navigate.push("Auth/Login");
```

The other childrens stack is named `Auth` and it's child screen is called `Login`. So in this case i'm saying go to this stack called `Auth` but specifically render the `Login` screen in that stack.

@satya164

### PR DESCRIPTION
**Pull request by satya164**
We now use the `params` of the route to determine `initialRouteName` and `initialParams` of a navigator.

So you can do something like this:

```js
navigation.push('Auth', { screen: 'Login', params: { token 'xxx' } })
```

This will navigate to the `Login` screen inside the `Auth` navigator.

Closes #90

### CODE REVIEW

**Comment by manticarodrigo** [comment]
@satya164 I have a root stack navigator with a dev sitemap screen, an auth stack, and tab stack with stacks for each of its screens.

These changes fix the problem I was having navigating from a screen inside a stack from my last tab to a screen in the first tab. I can make a `navigate('DashboardTab', { name: 'FilterScreen' })` call successfully. This renders the `FilterScreen`'s back button correctly and goes back to the initial route `DashboardScreen`.

However, this only works because the `DashboardTab` has already been navigated to when pressing the `TabStack` from the `SitemapScreen`.

When I make a `navigate('ConversationTab', { name: 'ConversationScreen' })` call, it now navigates to the correct screen, but no back button. The child screen becomes the initial route for that tab unless I explicitly navigate to the tab on my simulator before hitting the button on a screen from the last tab to navigate to that tab's child screen (and getting the back button).

I can reproduce the behavior using the root sitemap screen. I can navigate to child screens from my root-level sitemap screen to all the screens in my app, but it's only aware of the actual initial routes (rendering back button) of my stacks if I navigate to the tab or root screen within it beforehand.

Setting the `initialState` prop on `NavigationNativeContainer` for all these routes also does not fix the issue.

**Comment by satya164** [comment]
@manticarodrigo it's expected behaviour. if you have never navigated to a screen (the `initialRoute` in this case), we shouldn't put it in navgation history. current version of React Navigation does it and there is an issue open about it since it's not desirable behaviour: https://github.com/react-navigation/react-navigation/issues/6137

**Review by osdnk — CHANGES_REQUESTED** [review]
This API looks awkward for me. 
How about 

```
navigation.push('Auth', { screen: { screen: 'Login', params: { token 'xxx' } } })
```

**Comment by manticarodrigo** [comment]
@satya164 Is there preferred way of "deep linking" to un-initialized routes? In other words, how would I initialize my navigation history without having to navigate to it manually such that I can travel to any screen and retain the `initialRoute` of my choosing?

**Comment by satya164** [comment]
@manticarodrigo you can use `resetRoot` on the `ref` of the `NavigationNativeContainer` component to change the navigation state as you want. though we're currently missing a way to get the current rehydrated state. but we're planning to add it. we currently have some limited deep linking support (it doesn't preserve navigation state on subsequent links, but it'll change): https://reactnavigation.org/docs/en/next/deep-linking.html

**Comment by manticarodrigo** [comment]
@satya164 using `resetRoot` allows me to initialize state and define routes with their proper structure, specifically, setting a stack's `initialRoute`. However, both `resetRoot` and the `initialState` prop for `NavigationNativeContainer` are not respecting the `index` property state properties.

So this seems to be a way to "bootstrap" my route structure which then allows me navigate correctly with your new changes, however, it automatically renders the last route in the `routes` array for each level of the nested state.

**Comment by satya164** [comment]
> both `resetRoot` and the `initialState` prop for `NavigationNativeContainer` are not respecting the `index`
> it automatically renders the last route in the `routes` array for each level of the nested state.

They respect the `index` property. However, in a stack navigator, the `routes` array cannot contain more items after the `index`. The routes array contains the navigation history, not the routes you have defined.

If you're providing extra routes, the router will try to fix the invalid state and as a result uses the last item in the routes array. You shouldn't provide extra routes in the routes array. They will be automatically created when new screens are pushed.

**Comment by manticarodrigo** [comment]
@satya164 that makes sense. In the ticket you linked to for [3.11.1](https://github.com/react-navigation/react-navigation/issues/6137), someone suggested a partial fix by doing the following:

```
navigation.navigate({
  routeName: 'ChannelSettings',
  action: NavigationActions.navigate({
    routeName: 'NotificationSettings',
    params: { channelId }
  })
});
```

Is there an equivalent method in v5? Would this allow me to step into routes and allow them to initialize before the next action?

*Update:*
I can do subsequent `navigate` calls by wrapping them in a `setTimeout` to step into each stack before calling the next navigation action. Not sure if this is the correct way to do it or not.

**Comment by manticarodrigo** [comment]
@satya164 Any suggestions on how to do deeper navigations into uninstantiated routes? Using `setTimeout` seems hacky.

**Comment by satya164** [comment]
@manticarodrigo that's what this PR is aiming to solve.

also like I mentioned, you can also do `reset` to your new state.

**Comment by manticarodrigo** [comment]
@satya164 Ok but you previously said that there should not be an awareness of stack structure. This solves the navigation part, but it won't know my initial route unless I navigate to that stack beforehand.

Say for example, I have stack that pushes screens one after the next, following a specific order (i.e. registration flow). If I wanted to jump to a specific step, these changes solve that, however, the router has no idea which step of the stack this is, instead it makes that screen the initial route for the stack.

> @manticarodrigo it's expected behaviour. if you have never navigated to a screen (the `initialRoute` in this case), we shouldn't put it in navgation history. current version of React Navigation does it and there is an issue open about it since it's not desirable behaviour: [react-navigation/react-navigation#6137](https://github.com/react-navigation/react-navigation/issues/6137)

**Comment by satya164** [comment]
@manticarodrigo you are already able to do that with `reset`. like I mentioned, the problem you had with reset is because you pass more routes than you want to render. if you want to render 2 routes, pass 2 routes and it'll work. you don't even need to pass an `index`.

```js
resetRoot({
  routes: [
    { name: 'ChannelSettings' },
    { name: 'NotificationSettings', params: { channelId } },
  ],
});
```

we'll also make it possible to customize the router in future which will allow you to achieve any behaviour you want.

**Comment by manticarodrigo** [comment]
@satya164 Ok I was just able to do this now. Thank you!

**Comment by manticarodrigo** [comment]
@satya164 I get an error if I try to do a `resetRoot` from a nested child navigator. The same state works from a parent navigator screen:

```
resetRoot({
    routes: [
      {
        name: 'TabStack',
        state: {
          routes: [
            {
              name: 'ConversationTab',
              state: {
                routes: [
                  { name: 'ConversationListScreen' },
                  { name: 'ConversationScreen' },
                ],
              },
            },
          ],
        },
      },
    ],
  });
```

This is the expo error:

```
Invariant Violation: eventType argument is required.

This error is located at:
    in DashboardScreen (at SceneView.tsx:93)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:85)
    in EnsureSingleNavigator (at SceneView.tsx:84)
    in SceneView (at useDescriptors.tsx:109)
    in RCTView (at View.js:45)
    in View (at StackItem.tsx:157)
    in RCTView (at View.js:45)
    in View (at StackItem.tsx:156)
    in RCTView (at View.js:45)
    in View (at PointerEventsView.tsx:70)
    in PointerEventsView (at Card.tsx:807)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at Card.tsx:794)
    in PanGestureHandler (at Card.tsx:787)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at Card.tsx:783)
    in RCTView (at View.js:45)
    in View (at Card.tsx:772)
    in Card (at StackItem.tsx:125)
    in StackItem (at Stack.tsx:374)
    in RCTView (at View.js:45)
    in View (at Stack.tsx:106)
    in MaybeScreen (at Stack.tsx:367)
    in RCTView (at View.js:45)
    in View (at Stack.tsx:87)
    in MaybeScreenContainer (at Stack.tsx:326)
    in Stack (at StackView.tsx:275)
    in StackView (at createStackNavigator.tsx:69)
    in KeyboardManager (at createStackNavigator.tsx:67)
    in StackNavigator (at DashboardStack.tsx:17)
    in DashboardStack (at SceneView.tsx:93)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:85)
    in EnsureSingleNavigator (at SceneView.tsx:84)
    in SceneView (at useDescriptors.tsx:109)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.tsx:42)
    in RCTView (at View.js:45)
    in View (at ResourceSavingScene.tsx:26)
    in ResourceSavingScene (at BottomTabView.tsx:212)
    in RCTView (at View.js:45)
    in View (at screens.native.js:124)
    in ScreenContainer (at BottomTabView.tsx:202)
    in RCTView (at View.js:45)
    in View (at BottomTabView.tsx:201)
    in BottomTabView (at createBottomTabNavigator.tsx:43)
    in BottomTabNavigator (at TabStack.tsx:39)
    in TabStack (at SceneView.tsx:93)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:85)
    in EnsureSingleNavigator (at SceneView.tsx:84)
    in SceneView (at useDescriptors.tsx:109)
    in RCTView (at View.js:45)
    in View (at StackItem.tsx:157)
    in RCTView (at View.js:45)
    in View (at StackItem.tsx:156)
    in RCTView (at View.js:45)
    in View (at PointerEventsView.tsx:70)
    in PointerEventsView (at Card.tsx:807)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at Card.tsx:794)
    in PanGestureHandler (at Card.tsx:787)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at Card.tsx:783)
    in RCTView (at View.js:45)
    in View (at Card.tsx:772)
    in Card (at StackItem.tsx:125)
    in StackItem (at Stack.tsx:374)
    in RCTView (at View.js:45)
    in View (at Stack.tsx:106)
    in MaybeScreen (at Stack.tsx:367)
    in RCTView (at View.js:45)
    in View (at Stack.tsx:87)
    in MaybeScreenContainer (at Stack.tsx:326)
    in Stack (at StackView.tsx:275)
    in StackView (at createStackNavigator.tsx:69)
    in KeyboardManager (at createStackNavigator.tsx:67)
    in StackNavigator (at NavigationProvider.tsx:61)
    in EnsureSingleNavigator (at NavigationContainer.tsx:230)
    in ForwardRef(NavigationContainer) (at NavigationNativeContainer.tsx:30)
    in ForwardRef(NativeContainer) (at NavigationProvider.tsx:60)
    in NavigationProvider (at App.tsx:26)
    in StoreProvider (at App.tsx:24)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

removeAllListeners
    NativeEventEmitter.js:53:14
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:93:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:318:36
safelyCallDestroy
    ReactNativeRenderer-dev.js:14826:26
commitUnmount
    ReactNativeRenderer-dev.js:15328:32
commitNestedUnmounts
    ReactNativeRenderer-dev.js:15369:18
unmountHostComponents
    ReactNativeRenderer-dev.js:15649:27
commitDeletion
    ReactNativeRenderer-dev.js:15711:26
commitAllHostEffects
    ReactNativeRenderer-dev.js:16584:23
invokeGuardedCallbackImpl
    ReactNativeRenderer-dev.js:93:15
invokeGuardedCallback
    ReactNativeRenderer-dev.js:318:36
commitRoot
    ReactNativeRenderer-dev.js:16836:28
<unknown>
    ReactNativeRenderer-dev.js:18501:17
unstable_runWithPriority
    scheduler.development.js:255:23
completeRoot
    ReactNativeRenderer-dev.js:18499:4
performWorkOnRoot
    ReactNativeRenderer-dev.js:18427:21
performWork
    ReactNativeRenderer-dev.js:18324:24
performSyncWork
    ReactNativeRenderer-dev.js:18285:14
batchedUpdates$1
    ReactNativeRenderer-dev.js:18531:21
batchedUpdates
    ReactNativeRenderer-dev.js:2611:31
_receiveRootNodeIDEvent
    ReactNativeRenderer-dev.js:2706:17
receiveTouches
    ReactNativeRenderer-dev.js:2782:28
__callFunction
    MessageQueue.js:366:47
<unknown>
    MessageQueue.js:106:26
__guard
    MessageQueue.js:314:10
callFunctionReturnFlushedQueue
    MessageQueue.js:105:17
```

**Comment by satya164** [comment]
Please open a separate bug report with repro code. This is a pull request meant for pull request review.

**Pull request merged**
