### PR TITLE
feat: support headerLeft for native-stack

### PR DESCRIPTION
**Pull request by janicduplessis**
Same thing as `headerRight`. This is useful to customize the back button to use `Cancel` text for example.

### CODE REVIEW

**Comment by satya164** [comment]
Thanks for the PR. The reason it's not exposed is basically the same reason as https://github.com/react-navigation/navigation-ex/pull/159#issuecomment-549106370

On Android, `headerLeft` will remove both the title and back button. So it doesn't work like user would expect it to. I think we need to re-create the title and put it manually to make it work on Android.

**Comment by janicduplessis** [comment]
@satya164 Do you think this should be fixed in rn-screens instead?

**Comment by satya164** [comment]
@janicduplessis yeah. I think better to keep the integration a small wrapper and address issues in screens itself.

**Comment by janicduplessis** [comment]
Should we merge this then? :D

I can have a look at the issue when testing my app on Android

**Comment by satya164** [comment]
I'd rather wait for it to be fixed in screens first.

**Comment by radko93** [comment]
This is now fixed https://github.com/kmagiera/react-native-screens/commit/0919404b2e71839fc551c5c61f7001b3622ffd92

**Comment by osdnk** [comment]
Thank you for this contribution. Because we’re transferring the code to the main repository, I need to ask you for moving your PR to https://github.com/react-navigation/react-navigation 
Sorry for the inconvenience :)

**Pull request closed without merging**
